ARG BASE_IMAGE=silverbullet-base
FROM ${BASE_IMAGE}
RUN apt-get update && apt-get install -y --no-install-recommends \
    chromium \
    && rm -rf /var/lib/apt/lists/*
ENV CHROMIUM_PATH=/usr/bin/chromium
